
modLoader="javafml" #mandatory
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CrimsonCrips/RaiderBellRange" #optional
license="MIT"
[[mods]]
modId="raidingbellrange" #mandatory
#displayURL="https://www.curseforge.com/minecraft/mc-mods/alexs-mobs-interaction" #optional
version="1.0"
displayName="Raiding Bell Range"
authors="The Crimson"

description='''Configurable Range for giving glowing to raiders when hitting a bell'''

[[dependencies.raidingbellrange]]

modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.raidingbellrange]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"